### ISSUE TITLE
Mobs still spawning?

### ISSUE THREAD

**Issue by saltworthybutler** [Darkhax-Minecraft/BadMobs#10]
Hi! Terribly sorry if I end up being the dumb one here who's missing something but I cannot get the mod to work. I'm playing in 1.7.10, I have other mods, I can give them to you if you need them I've done configurations through both just the minecraft files as well as the minecraft loading screen. Everything is lowercase, spelled correctly, so I'm not sure if I'm doing something wrong, or if there's something wrong with the mod. If you need any other information from me let me know, the game isn't crashing or anything the mobs themselves are just still spawning when I don't want them too. Thank you!

**Comment by darkhax** [comment]
The 1.7.10 ids are different than the 1.12 ones. 1.12 would be minecraft:zombie and 1.7.10 would be Zombie with an upper case.

**Comment by saltworthybutler** [comment]
@darkhax I tried that. Am I editing it wrong or something? Or are there any mods that you know conflict with this mod?
