### ISSUE TITLE
Mobs still spawning

### ISSUE THREAD

**Issue by andrewq99** [Darkhax-Minecraft/BadMobs#11]
hear my config did i do something wrong because Mobs still spawning

# Configuration file

general {
    # When enabled, the ID of a mob will be shown on it's corrosponding spawn egg. This is used to help you blacklist mobs. [default: true]
    B:addTooltipInfo=true

    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        minecraft:Skeletons
        minecraft:Zombies
        minecraft:Creepers
        minecraft:Spiders
        minecraft:Cave Spiders
        minecraft:Endermen
        minecraft:Slimes
        minecraft:Witches
        minecraft:Silverfish
        minecraft:Endermites
        minecraft:Guardians
        minecraft:Elder Guardians 
     >

    # When enabled this mod will target mobs that have already spawned. This option must also be enabled to prevent mob spawners from spawning as well. [default: true]
    B:removeAggressively=true

    # While false, this mod will not remove custom named mobs from the game. [default: false]
    B:removeNamedMobs=false
}

**Comment by darkhax** [comment]
All of your ids are wrong. Minecraft IDs must be all lower case, and can not contain spaces. Also you have an extra s on a lot of these. 

`minecraft:Zombies` should be `minecraft:zombie`
`minecraft:Elder Guardians ` should be `minecraft:elder_guardian`

You can find a full list of IDs on [this](https://minecraft-ids.grahamedgecombe.com/entities) website. You can also hover your mouse over a spawn egg in game and my mod will show the correct ID on the tooltip.

**Comment by MoonSnowTV** [comment]
I have the exact same issue now, I did what Darkhax said and it still does not work.
