### ISSUE TITLE
nope still spawning and i did what you toll me to do

### ISSUE THREAD

**Issue by andrewq99** [Darkhax-Minecraft/BadMobs#12]
# Configuration file

general {
    # When enabled, the ID of a mob will be shown on it's corrosponding spawn egg. This is used to help you blacklist mobs. [default: true]
    B:addTooltipInfo=true

    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        minecraft:elder_guardian,minecraft:creeper,minecraft:skeleton,minecraft:spider,minecraft:giant,minecraft:zombie,minecraft:slime,minecraft:enderman,minecraft:cave_spider,minecraft:silverfish,minecraft:witch,minecraft:guardian
     >

    # When enabled this mod will target mobs that have already spawned. This option must also be enabled to prevent mob spawners from spawning as well. [default: true]
    B:removeAggressively=true

    # While false, this mod will not remove custom named mobs from the game. [default: false]
    B:removeNamedMobs=false
}

**Comment by darkhax** [comment]
They must be on a new line, and not have a , between them.
