### ISSUE TITLE
Explosive ocelot spawning

### ISSUE THREAD

**Issue by Waynekosimoto** [Darkhax-Minecraft/BadMobs#15]
I wanted to get rid of all fantasy mobs from the game because I'm trying to create a realistic modpack. For some reason, I'm getting insane ocelot spawning. It makes the game unplayable due to the lag.

Here's my config:
https://hastebin.com/obumihibof.bash

This is a screenshot:
![2018-12-12_23 48 25](https://user-images.githubusercontent.com/12769365/49907286-37f30880-fe3b-11e8-83de-3b7a8ffea1ab.png)

**Comment by darkhax** [comment]
This mod only prevents mobs from spawning, and will never directly cause a mob to spawn. My best guess is that removing these mobs has opened up the mob cap to where only ocelots can spawn in that biome.

**Comment by Waynekosimoto** [comment]
That doesn't explain the 10 ocelots spawning every second issue
