### ISSUE TITLE
Mobs with Meta

### ISSUE THREAD

**Issue by Sarous** [Darkhax-Minecraft/BadMobs#16]
Not sure if this is a bug, my own ignorance, or a suggestion. I am attempting to ban only certain minecraft:villager from spawning, namely {Profession:5}, but am unsure how, or if, the blacklist is able to accept metavalues in the entry?

**Comment by Darkhax** [comment]
Thanks for the issue/suggestion. This is currently not possible with this mod, and not a feature that I am planning to add. This mod is meant to be a quick fix for removing annoying mobs from the game. For more complex things and modpack purposes, you should look into McJty's InControl mod.
