### ISSUE TITLE
Show Mob ID on spawn egg tooltips when advanced tooltips are enabled

### ISSUE THREAD

**Issue by LuminescentMoon** [Darkhax-Minecraft/BadMobs#19]
Show Mob ID on spawn egg tooltips when `Minecraft.gameSettings,advancedItemTooltips` is `true` regardless of BadMobs's config's `addTooltipInfo` state. This will make BadMobs follow Minecraft's debug tooltip convention. `Minecraft.gameSettings,advancedItemTooltips` is publicly accessible but is an instance field so an instance of Minecraft will need to be obtained.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I will include this change in the 1.15.2 port of the mod.
