### ISSUE TITLE
Pillagers still attack villages

### ISSUE THREAD

**Issue by BourotBenjamin** [Darkhax-Minecraft/BadMobs#20]
Try to add the mod on my server.

Config : 
    
    bannedMobs = ["minecraft:pillager"]    

But pillagers attacked my vilage even if they shouldn't spawn.

- forge-1.14.4-28.1.1
- BadMobs-1.14.4-3.0.1

**Comment by Darkhax** [comment]
Please read https://github.com/Darkhax-Minecraft/BadMobs/issues/18 for more information.

**Comment by BourotBenjamin** [comment]
@Darkhax I saw this post but you just list the different spawn reasons the game use, but not the one you support (or not).

As they spoke about spawners, and it was a village I made mysefl ( so I don't have a spawner in the village ), I wasn't sure it was the same issue.

So I stay tuned for an update to be able to disable them ;)
