### ISSUE TITLE
Can't ban mobs in multiple dimensions

### ISSUE THREAD

**Issue by dirtsword** [Darkhax-Minecraft/BadMobs#23]
I added a mob and the dimension ID (Twilight Forest ID 7) I did not want them to spawn in and it worked great:   From the badmobs.cfg file:

_# A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
S:bannedMobs_ <

_minecraft:zombie#7_

_>_

But I also want to ban mobs from an additional dimension: Erebus ID 66.  I haven't been able to get it to work.  I tried both of these options:

_minecraft:zombie#7,66
minecraft:zombie#7,#66_

Any suggestions?

-Minecraft 1.12.2
-BadMobs-1.12.2-1.1.28
-Forge 14.23.5.2831

**Comment by Darkhax** [comment]
Try 
```
minecraft:zombie#7
minecraft:zombie#66
```

**Comment by dirtsword** [comment]
Yes that works. Thank you!

**Comment by Darkhax** [comment]
Glad it worked.
