### ISSUE TITLE
Config option disable

### ISSUE THREAD

**Issue by Harrym15** [Darkhax-Minecraft/BadMobs#24]
Please help, when I go to the mods tab and click the mod the config button is disabled. Any Solutions?

**Comment by Darkhax** [comment]
That means there is no Config GUI. You will have to edit the file yourself.

**Comment by Harrym15** [comment]
That makes sense. Thank you. But whats the ID for Silverfish?

**Comment by Harrym15** [comment]
Trying to disable Silverfish Spawner's and Spawn Eggs.
