### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by Magnic** [Darkhax-Minecraft/BadMobs#25]
It just doesn't work. No amount of different ways i put the mob id ever turned out with anything different than 1s of menu with squares without letters and loop of loading the menu. Either fix it, or give a proper instructions how to add mobs to blacklist.

**Comment by Darkhax** [comment]
The mod is tested and works fine, and the instructions for adding mobs is clear. Meanwhile your issue is critical info such as game version, mod version, and logs. You're also being pretty rude so no thanks.
