### ISSUE TITLE
[1.15] Idk how to describe this

### ISSUE THREAD

**Issue by i-o-u** [Darkhax-Minecraft/BadMobs#26]
It freezes on the loading screen for a REALLY long time and then it starts showing this over and  over until I close it:

![LoadingScreen](https://user-images.githubusercontent.com/60834747/77221341-197ecf80-6b9d-11ea-8cc1-22f2a2c83fa0.gif)

[Here's the log](https://pastebin.com/FnpKGp4Q)

**Comment by Darkhax** [comment]
Your config file is written incorrectly. You need to quote the value. So "minecraft:drowned" instead of minecraft:drowned.

**Comment by i-o-u** [comment]
Thanks I thought it might've been a problem on my side

**Comment by i-o-u** [comment]
I just changed it and it's still doing it

[https://pastebin.com/K3rZ8Yd7](https://pastebin.com/K3rZ8Yd7)

**Comment by Darkhax** [comment]
Can you please upload the config file?

**Comment by i-o-u** [comment]
I just got it to work by adding commas
