### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by mcfensi** [Darkhax-Minecraft/BadMobs#27]
Cannot be used in the server。
[crash-2020-04-03_22.09.37-server.txt](https://github.com/Darkhax-Minecraft/BadMobs/files/4427770/crash-2020-04-03_22.09.37-server.txt)

**Comment by Darkhax** [comment]
You're using a 1.14.4 version on 1.15.2, this does not work.

**Comment by mcfensi** [comment]
I am using version 1.15.2, which works in single player games, but not on the server. Glad it was fixed in 5.0.2. Thank you
