### ISSUE TITLE
killMode on false kills mobs that spawns out of spawn eggs

### ISSUE THREAD

**Issue by bluefutureMC** [Darkhax-Minecraft/BadMobs#3]
I need a mod that can prevent mobs from spawning naturally, I think thats what "killMode" does right?
if it is then it doesn't work, if this feature is not only preventing natural spawn, then I need a mod that can do that.

**Comment by darkhax** [comment]
killMode is not related to natural/unatural spawns. killMode marks the mob as dead in addition to preventing the spawn, which will prevent all those mobs from re-entering the world if the mod is removed.
