### ISSUE TITLE
[1.15.2] Doesn't work on Lycanites Mobs

### ISSUE THREAD

**Issue by Geethebluesky** [Darkhax-Minecraft/BadMobs#31]
Not sure what else to say, but it doesn't work. 

Trying to get rid of a specific Lycanite's Mob. Here's my [config file](https://pastebin.com/yqF1nUcg) for your mod.

The entity name is verified as correct. 
I want to disable that mob since it's currently crashing my game on render, so I disable it everywhere (eggs and spawners incuded). But the mob still spawns in a vanilla spawner.

**Comment by Darkhax** [comment]
Unfortunately some mods use custom spawning mechanics that can not be prevented by the mod. In some versions there is a "remove aggressively" or "killmode" config option which can be used to remove them the moment they spawn into the world.
