### ISSUE TITLE
Won't prevent pillagers

### ISSUE THREAD

**Issue by ZAKsPop** [Darkhax-Minecraft/BadMobs#32]
I keep getting pillagers spawning near my house.
BadMobs-1.15.2-5.0.2.jar

#General settings for the mod.
[general]
	#A list of all banned mobs. If a mobs entity id is added to this list, it will not be allowed to spawn in any world.
	bannedMobs = ["minecraft:creeper", "minecraft:pillager", "minecraft:skeleton", "minecraft:zombie", "minecraft:witch", "minecraft:vindicator", "minecraft:drowned", "minecraft:husk", "minecraft:zombie_villager", "minecraft:squid"]
	#Should banned mobs spawn from spawners?
	allowSpawners = false
	#Should banned mobs spawn from spawn eggs?
	allowSpawnEgg = false

Any idea what it might be?

**Comment by Darkhax** [comment]
Pillager spawning isn't considered natural so this mod won't work.
