### ISSUE TITLE
[1.12.2]  Does not work

### ISSUE THREAD

**Issue by Accelerator-T** [Darkhax-Minecraft/BadMobs#33]
hello could you help me? 
I write everything correctly (maybe not) but mobs continue to spawn

# Configuration file

general {
    # When enabled, the ID of a mob will be shown on it's corrosponding spawn egg. This is used to help you blacklist mobs. [default: true]
    B:addTooltipInfo=true

    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        minecraft:creeper
        minecraft:skeleton
        minecraft:spider
     >

    # When enabled this mod will target mobs that have already spawned. This option must also be enabled to prevent mob spawners from spawning as well. [default: false]
    B:removeAggressively=false

    # While false, this mod will not remove custom named mobs from the game. [default: false]
    B:removeNamedMobs=false
}

**Comment by Darkhax** [comment]
By default the mod only stops natural mob spawning. Spawners, spawn eggs, and other mechanics can still spawn them. Set removeAggressively to true if you want to remove everything else.

**Comment by Accelerator-T** [comment]
thanks it works
