### ISSUE TITLE
Config option not working

### ISSUE THREAD

**Issue by SunnyCirrus** [Darkhax-Minecraft/BadMobs#34]
Whenever I go under mods, the 'config' button isn't clickable. 
![bad mobs](https://user-images.githubusercontent.com/72773330/95803013-03696580-0ccd-11eb-93ca-9c99f1ceef09.JPG)

**Comment by Darkhax** [comment]
Some versions don't have a config GUI option. You will need to edit the file manually.

**Comment by Gitbauser** [comment]
And how do you do it "manually"?

**Comment by Gitbauser** [comment]
...how?

**Comment by Gitbauser** [comment]
...but how?
