### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by Gitbauser** [Darkhax-Minecraft/BadMobs#35]
I am currently using minecraft 1.12.2 and this mod is unable to do what is was designed to do. The "config" button is unclickable and i can't "edit it manually". Now this wouldn't be so much of a problem if i could search up the answers on the internet but guess what, no results! Anyways if someone could give me HELPFUL/USEFUL advice, that would be very much appreciated.
![2020-11-11_18 28 18](https://user-images.githubusercontent.com/74314765/98843828-c4edd480-244b-11eb-8c47-4f0c1a822429.png)

**Comment by Darkhax** [comment]
There is no GUI to edit the config, you will have to edit it manually. The file is in the /config folder of wherever your Minecraft is installed.
