### ISSUE TITLE
How to config GUI?

### ISSUE THREAD

**Issue by DuphyDog** [Darkhax-Minecraft/BadMobs#36]
Hello,
I suffer from severe arachnophobia and even spiders in Minecraft gives me real anxiety and panic attacks. 
I was trying to get BadMobs to work several hours. I probably have same problem as my predecessors with GUI, since I can't open the "config" panel in launcher. I tried to find some info on how to fix this issue, but I couldn't find any.
Would you please explain how to fix this problem?
Thank you.

**Comment by Darkhax** [comment]
The config GUI only works on certain versions of the game. If it's not showing up for you then it is not supported on your version. This is because Forge keeps changing how the GUI works and on many versions they remove support without adding it back. 

In your case you would need to find the config folder manually, it's normally in .minecraft/config and is named something like bad-mobs.cfg or bad-mobs.toml.

**Comment by DuphyDog** [comment]
Yup, found that. Unfortunately I'm not able to open it or do something about it. Now it just came to my mind, that the problem might be that I'm using MacOs?
![Snímek obrazovky 2020-12-21 v 17 19 49](https://user-images.githubusercontent.com/76441261/102798006-c7c7d780-43b0-11eb-89a1-ce28765e5fa4.png)

**Comment by Darkhax** [comment]
MacOS works fine, the issue is that you've never opened this type of file before so your computer doesn't know which app/program to read it with. TOML is just a normal text file. I believe you want to open it with "TextEdit" which should already be on your computer by default.

**Comment by DuphyDog** [comment]
Okay, thank you. I thing I might wrote what I needed to. I don't want spiders to ever spawn, I don't mind witch to spawn.
![Snímek obrazovky 2020-12-21 v 17 34 59](https://user-images.githubusercontent.com/76441261/102799566-02327400-43b3-11eb-8d12-2c0845938a60.png)
I only changed true to false and false to true but what I got is this error message.
![Snímek obrazovky 2020-12-21 v 17 36 36](https://user-images.githubusercontent.com/76441261/102799679-22fac980-43b3-11eb-9983-1f34267276e2.png)

**Comment by Darkhax** [comment]
Can you click the "open crash-20020-....." button and upload the file here?

**Comment by DuphyDog** [comment]
Sure, here you go.
[crash-2020-12-21_17.47.45-fml.txt](https://github.com/Darkhax-Minecraft/BadMobs/files/5725447/crash-2020-12-21_17.47.45-fml.txt)

**Comment by Darkhax** [comment]
Ah I see, forge's new system is a bit annoying and likes to crash at every little typo. 

> Invalid value flase

Simple typo, should work when you fix it.

**Comment by DuphyDog** [comment]
It finally works and doesn't spawn any spiders when using egg in creative. Thank you so much for your help!

**Comment by Darkhax** [comment]
That's great. Glad I could help.
