### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by wutdahack** [Darkhax-Minecraft/BadMobs#39]
Would you consider making a fabric version of this mod? If not it's okay and if you know a mod like this, please tell me what it's called and where I'd get it from.

**Comment by Darkhax** [comment]
I am in the process of adding Fabric support to my mods, although it's not an active priority for me.

**Comment by wutdahack** [comment]
Okay, thanks for replying.

**Comment by ccrowles** [comment]
> I am in the process of adding Fabric support to my mods, although it's not an active priority for me.

Do you still plan to support it? Asking because the answer was from a year ago ~~and because I'm going insane with a pillager outpost right near the perfect place for my base~~

**Comment by Darkhax** [comment]
@ccrowles Yes there are still plans, but it's still not an active priority.

**Comment by ccrowles** [comment]
I see, thanks for the answer!
