### ISSUE TITLE
noob needs help 1.12.2 config

### ISSUE THREAD

**Issue by lilacbuni** [Darkhax-Minecraft/BadMobs#41]
I dont understand what im doing wrong? im trying to edit the config using notepad++ but mobs still show up naturally and unnaturally? how do i enter this properly? (i also have forge thats why i have to config edit)

![dre](https://user-images.githubusercontent.com/79282052/108414767-84f57500-7224-11eb-913f-9787ceb27ccf.PNG)

![dghd](https://user-images.githubusercontent.com/79282052/108414916-b40be680-7224-11eb-8f64-41d05a3ed9fe.PNG)

**Comment by Darkhax** [comment]
The ID shouldn't have brackets around them.
