### ISSUE TITLE
forge server doesnt let me config/ doesnt have config file for badmobs

### ISSUE THREAD

**Issue by terminator57012** [Darkhax-Minecraft/BadMobs#44]
when i go to remove the mobs i dont want, the config file for badmobs doesnt exist. i tried copying the one from my normal mods folder, it did not work. please let me know how i can config this mod on a forge server

**Comment by terminator57012** [comment]
i am on version 1.12.2

**Comment by terminator57012** [comment]
i also heard there was a way to make it a server mod but idk how to do that

**Comment by Darkhax** [comment]
The config is generated when the mod is loaded. If the config is not generated for you then the mod has not been installed properly or has been prevented from loading.
