### ISSUE TITLE
Mod does not retain changes to toml file

### ISSUE THREAD

**Issue by smmmadden** [Darkhax-Minecraft/BadMobs#45]
I've just installed this mod on my MP Server and see all the settings in the badmobs-common.toml file, but every time I change them they keep getting reset back to default values.
I've tried with the server up, edited the file, save it and it gets reset immediately.
I've tried shutting down the server, changing the file settings and restarted it.  The settings again are reset to their defaults.
The ones I did try to change (doesn't seem to matter since all get wiped out) are Ghast (rows: 1042, 1044 and 1048) and Piglin (rows: 382, 384 and 388)
Forge Version: 36.0.43
Minecraft: 1.16.5
BadMobs: 9.0.1
Latest Log (restarted with changes above): https://pastebin.com/u2b5kEM4
Thanks - Steve

**Comment by Darkhax** [comment]
Hello, this is related to a change Forge made to their config system. I will have a fix for it out soon.

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/BadMobs/commit/bc60be470033a1bee8f7a37f67e06e3ef17468d3
