### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tmo71802** [Darkhax-Minecraft/BadMobs#47]
im not very good with all this but i would like to know if there is a version of badmobs that would work with this modpack if so how would i go about setting it up
![IMG_0809](https://user-images.githubusercontent.com/81128710/111931405-85866300-8a91-11eb-8bda-d05548d0fd79.jpg)

**Comment by Darkhax** [comment]
Download the latest Minecraft 1.12.2 JAR file from the files page. Then put it in the mods folder for this pack.
