### ISSUE TITLE
Underscore in ID prevents spawn control.

### ISSUE THREAD

**Issue by xyifer12** [Darkhax-Minecraft/BadMobs#5]
Any vanilla mob with an underscore in the ID spawns regardless of config settings.
Examples: Magma_cube, Zombie_villager, Skeleton_horse.

Tested in forge 14.23.0.2546 and 14.23.0.2512, mod version 1.0.22.

**Comment by darkhax** [comment]
Thanks for reporting this issue. It's related to legacy code in the vanilla game that hasn't been updated yet. This has been fixed in the next version. Also keep in mind that casing is important. So magma cubes would be `minecraft:magma_cube`.
