### ISSUE TITLE
This is broken for 1.12.2

### ISSUE THREAD

**Issue by FrankGamingNFuck** [Darkhax-Minecraft/BadMobs#50]
I went into the config file and did 
minecraft:pig for a test. And for some reason pigs were still spawning

**Comment by Darkhax** [comment]
The mod has been thoroughly tested and confirmed to work on 1.12.2. Here are some debugging steps you can do to help find your error.

1. Make sure the mod is properly installed. The JAR file should be in the mods folder, and the mod should be listed in the ingame mod list.
2. Make sure you saved your changes to the config file.
3. Make sure the ID of the mob is correct.
4. Make sure the config file has been formatted properly. Example included below.
5. Hot-reloading config files is unreliable, make sure you restart the game. 
6. Previously spawned mobs are not removed by default. Try in a new world or enable remove aggressively.
7. Spawn eggs, mob spawners, and other forms of forced spawning bypass this mod by default. Try enabling remove aggressively.

**Example**
```cfg
# Configuration file

general {
    # When enabled, the ID of a mob will be shown on it's corrosponding spawn egg. This is used to help you blacklist mobs. [default: true]
    B:addTooltipInfo=true

    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        minecraft:creeper
        minecraft:witch
        minecraft:skeleton
     >

    # When enabled this mod will target mobs that have already spawned. This option must also be enabled to prevent mob spawners from spawning as well. [default: false]
    B:removeAggressively=true

    # While false, this mod will not remove custom named mobs from the game. [default: false]
    B:removeNamedMobs=false
}
```
