### ISSUE TITLE
Mobs aren't getting removed 1.7.10

### ISSUE THREAD

**Issue by devinat1** [Darkhax-Minecraft/BadMobs#53]
Here is my config:
However, the mods in the bannedMobs list are not removed from the game when I re-launch!

# Configuration file

general {
    # A list of all banned mobs. If a mobs entity name is added to this list, it will not be allowed to spawn in any world. To get the name of an entity, interact with it using the data checker and it's name will be given. [default: [example1], [example2], [example3]]
    S:bannedMobs <
        minecraft:spider
        minecraft:skeleton
        minecraft:bat
	minecraft:creeper
	minecraft:cave_spider
     >

    # If this is set to true, bad mobs will be killed/deleted when they attempt to spawn. If this is set to false, the mob will not be removed from the world and only the spawning will be prevented, and when the mob is nolonger listed as bad, all previously prevented mobs of that type will spawn. [default: true]
    B:killMode=false

    # If this is set to true, the mod will be put into server-side mode. This will remove the Entity Data Book from the game, but will allow clients to connect to your server, without having the mod installed. [default: false]
    B:serverMode=false
}

****

**Comment by Darkhax** [comment]
You're using the wrong mob IDs. Those IDs are for newer versions of the game only. 1.7.10 is ancient and unsupported by virtually everything so you may have a hard time finding the correct ones, but they should be available in game using commands. I don't remember all of the IDs but I believe the ID for zombies is `Zombie`.
