### ISSUE TITLE
Hoglins keep spawning, and they're invisible

### ISSUE THREAD

**Issue by exentio** [Darkhax-Minecraft/BadMobs#54]
I'm running the mod on 1.16.5, the title is self-explanatory of the issue. This happens both in the nether and with spawn eggs. Using `/kill @e[type=minecraft:hoglin]` works every time, implying mobs never stopped spawning. The relevant part of the config (I didn't change anything else):
```
    [minecraft.hoglin]
        #Should the entity be allowed to spawn normally?
        allowNormalSpawning = false
        #Should spawners be able to spawn the entity?
        allowSpawners = false
        #Should spawn eggs be able to spawn the entity?
        allowSpawnEggs = false
        #When enabled the entity type will be aggresively removed from worlds. This will bypass all other options.
        removeAggressively = true
```

Feel free to ask for anything else that could be useful to solve the issue.

**Comment by Darkhax** [comment]
Are you playing on a server? When playing on a server the server will need to have this mod installed and the config files must match.

**Comment by exentio** [comment]
Yes, I'm playing on a server, but it has the mod too and the same exact config file

**Comment by Darkhax** [comment]
From what you described this issue sounds like the client and server are not agreeing on which mobs should be banned. An invisible mob without the invisibility potion would suggest that the mob was despawned on the client/render thread but not on the logic/server thread. Please double check the logs on the server to make sure the mod is being loaded. You may also need to restart the server for changes to the config file to be loaded.

**Comment by exentio** [comment]
The server owner found no errors regarding the mod in the log, and I know for sure that the config on client and server is exactly the same because the files are shared

**Comment by Darkhax** [comment]
I've tried a bit to reproduce this issue with little luck. With just this mod and Forge installed on both the client and server it works exactly as expected. The only way I was able to reproduce the issue was by not installing the mod on the server, or by having a different config file loaded on the server.
