### ISSUE TITLE
Unspecified crash when joining fresh vanilla world.

### ISSUE THREAD

**Issue by xyifer12** [Darkhax-Minecraft/BadMobs#6]
**Issue**
Attempting to join any vanilla world, new or old, results in a crash with no launcher description.
- - -
**How To Reproduce**
Install the latest forge & the latest version of BadMobs.
Create new world, then try to join.
- - -
**Versions**
Java 8 151
Forge 14.23.0.2549, Forge 14.23.0.2546, Forge 14.23.0.2512
BadMobs 1.0.23
- - -

fml-client-latest.log - https://pastebin.com/TFYS3nG7

**Comment by darkhax** [comment]
Thanks for reporting this issue. I will try to have a fix out promptly.

**Comment by darkhax** [comment]
The new version (1.0.24) has been uploaded to curse. It is currently awaiting approval, but will be available for download [here](https://minecraft.curseforge.com/projects/bad-mobs/files/2501922)

**Comment by lukiono** [comment]
Thanks for your fast work =)
