### ISSUE TITLE
Mobs still seem to be there invisible [Server] [1.18.2]

### ISSUE THREAD

**Issue by zEpiixz** [Darkhax-Minecraft/BadMobs#64]
I deactivated mobs from various mobs with the config for simple spawning. 
Then today i saw some duck eggs on the ice and heard quacking. I heard them walking on the ice and one of them laid another egg.
They been invis and invulnerable. Like they are there but also not.
Firge 40.1.52 in 1.18.2

**Comment by Darkhax** [comment]
This issue is caused by the mod not being installed on the server, or the server not having the same config as the client. The server and the client both need the mod, and they both need the same config.
