### ISSUE TITLE
config file doesn't appear

### ISSUE THREAD

**Issue by Kayro098** [Darkhax-Minecraft/BadMobs#65]
I installed bad mobs for 1.12.2 and there is no .cfg file in the config folder in .minecraft
![unknown](https://user-images.githubusercontent.com/109516918/179486306-35a67951-983d-4174-9d13-f28656421ae9.png)

**Comment by Darkhax** [comment]
Make sure you have run the game until the title screen once for the files to generate. If the file is not there, you are looking in the wrong folder.
