### ISSUE TITLE
Got a question

### ISSUE THREAD

**Issue by kade7263** [Darkhax-Minecraft/BadMobs#66]
So, I want to install this mod because I want to install a mod called critters and companions along with biome makeover. However, both these mods add their own versions of dragon flies. Is there a way to use bad mobs to disable just the dragonf lies from critters and companions from spawning? How would I specify that I want to remove just the dragonflies from that mod?

**Comment by Darkhax** [comment]
Yes, you can disable individual mobs using this mod. If you're in a newer version of the game each mob has it's own section in the config file and you just need to find the specific one you want to disable. In older versions you need to add the specific mob ID to a list that should be removed. The mobs will have different IDs.
