### ISSUE TITLE
[Tutorial] I have no idea how to ban modded mobs 

### ISSUE THREAD

**Issue by DoveGirl777** [Darkhax-Minecraft/BadMobs#67]
I did open the config file in notes but in the example section, I don't know how to insert the command for certain mobs to be banned. 

I use these mods:

**Screenshot**
![Screenshot 2022-08-13 152400](https://user-images.githubusercontent.com/40477211/184508425-166906ba-9e3f-411f-abca-76a4b00be869.png)

**Versions**
-Minecraft 1.12.2
-Forge 14.23.5.2855
-badmobs mod 1.1.40

**Comment by DoveGirl777** [comment]
I also tried to watch videos online but it only showed vanilla mobs. I'm trying to get rid of an individual mob from a specific mod, called zawa.

**Comment by Darkhax** [comment]
Modded mobs are banned the same way as any vanilla mob. You will need to find the ID of the mob you want to disable and simply put it in the config file. You can find the ID of a mob easily by turning `addTooltipInfo` to true in the config file, and then looking at the spawn egg of the mob in Creative Mode.
