### ISSUE TITLE
Iron Golems still spawn despite config

### ISSUE THREAD

**Issue by TheCrazyGuy15052** [Darkhax-Minecraft/BadMobs#68]
I have a large village where iron golems very regularly spawn. when i set the config so that they would stop spawning altogether, i still find them spawning per norm.

`#Spawning options for minecraft:iron_golem
	[minecraft.iron_golem]
		#Should the entity be allowed to spawn normally?
		allowNormalSpawning = false
		#Should spawners be able to spawn the entity?
		allowSpawners = false
		#Should spawn eggs be able to spawn the entity?
		allowSpawnEggs = false
		#Should the entity spawn via mob conversion? i.e. villager -> zombie
		allowConversions = false
		#When enabled the entity type will be aggresively removed from worlds. This will bypass all other options.
		removeAggressively = true
`

Mod version 1.19.2-16.1.2
Forge version 43.1.38

Ran on a Multiplayer Server

**Comment by Darkhax** [comment]
Unfortunately there is a bug in Forge that allows certain edge cases to still spawn. They are hopefully fixing this on 1.19.4. Alternatively you can use the In-Control mod which seems to work a bit more reliably, but still has issues.
