### ISSUE TITLE
Mobs still spawn

### ISSUE THREAD

**Issue by DuckysClips** [Darkhax-Minecraft/BadMobs#71]
i dont know how to fix this, im using it on 1,12,2. i have googled it and many people seem to have this problem and they have to go into the config. when i do that there is 5000 strings of code and i dont want to sit here for a whole day. how can i fix this?

**Comment by lBelic060589** [comment]
same problem bro

**Comment by Lovelies23** [comment]
im using 1.19.2, i just updated it and all my configs changed, after i re did every mob, they still kept spawning naturally, this update isnt doing what its suppose to

**Comment by Darkhax** [comment]
> when i do that there is 5000 strings of code and i dont want to sit here for a whole day. how can i fix this?

This mod isn't meant to disable every mob spawn, it's meant to allow players to disable very specific mobs from their world. If you really want to disable everything you can use a text editor like Notepad++ that has a find and replace option to replace all instances of a given string. Just be careful not to disable anything important like players, minecarts, etc.
