### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by JustVynlier** [Darkhax-Minecraft/BadMobs#73]
theres no config file for the bad mobs mod when i go to config, ive looked online for about an hour now and I can't find anything that has helped me figure this out
![config 3_13_2023 2_53_54 PM](https://user-images.githubusercontent.com/127790784/224817645-ff2ab140-f8d6-4686-b2e0-ae27696c05e7.png)

honestly no clue what to do, tired of mobs spawning on top of flying mobs and killing me(trying to make a zombie world)

**Comment by JustVynlier** [comment]
oh yeah i have a learning disability so please dont reply and close it immediately, im probably gonna ask more questions

**Comment by Darkhax** [comment]
The config file is named `badmobs-common`, it's the 3rd file from the top in your screenshot. I am closing this because GitHub is for issue reports, not tech support or Q&A. 
![image](https://user-images.githubusercontent.com/2250798/224931509-65280778-fcb2-443b-b5cd-850786cad2f6.png)
