### ISSUE TITLE
Bad Mobs won't work

### ISSUE THREAD

**Issue by Plantor07** [Darkhax-Minecraft/BadMobs#75]
I used BadMobs in a zombie apocalypse modpack for 1.16.5 forge so that only zombies would spawn out of the hostile mobs and it worked amazing and did exactly what it needed to do but then the day after I got back on the the modpack it stopped working. I thought it was because I changed something in a different mod the Improved mobs mod( I changed some of the value and how parts of it worked as well as the light level everything will spawn at) or the farsighted mobs mod( I changed the sight of the mobs over what was set in the modpack). I tried looking at the config file to see if everything was fine and it was. then I tried reinstalling the Bad mobs mod, that didn't work. I deleted and reinstalled both the mobs I talked about and it still didn't work. so then I deleted all of my worlds deleted the mod and then reinstalled the mod and it still didn't work when I opened up minecraft. Is there anyway that you can help me because your mod is really cool and I have no Idea what to do

**Comment by Darkhax** [comment]
Nothing has changed in the mod, especially not on 1.16.5 so I am not sure why it stopped working or how I can help you. For advanced use cases like this I would recommend using a mod like InControl, as it will give you better control over mob spawning.

**Comment by Plantor07** [comment]
I was using incontrol to increase zombie spawns but I don't know how to use it to stop mobs from spawning. could you give me a bit of code that I could use to do the same thing that bad mobs does

**Comment by Darkhax** [comment]
I have not used InControl myself, I would try reading their docs or trying to find their support channels.

**Comment by Plantor07** [comment]
ok thanks
