### ISSUE TITLE
Config keeps regenerating when mod loads

### ISSUE THREAD

**Issue by qwertymash** [Darkhax-Minecraft/BadMobs#78]
I tried reinstalling the mod and all, but my changes don't save at all when re-entering Minecraft. (the config file decides to regenerate with default values)
I tried copy-pasting a config from another modpack, but guess what, the config still regenerates, no changes being saved, all done when Minecraft was closed.

**Comment by qwertymash** [comment]
When entering the other modpack and the mod loads, the config file stays the same.

**Comment by AveragePizza** [comment]
ive got the same issue here adding to it that the mobs are invisible and still make noises and attack, was it a mod conflict that you had

**Comment by qwertymash** [comment]
i kept trying, yet still doesnt work. 6-7 days later... still no support... very great support team....

**Comment by qwertymash** [comment]
whoops.

**Comment by Darkhax** [comment]
@samz0261 It's a free project ran by hobbyists, there is no support team. 

The config file is regenerated by Forge when it detects invalid user input.

**Comment by Darkhax** [comment]
@AveragePizza The mobs are invisible when the config file on the client and server do not match.
