### ISSUE TITLE
Mod Not Working modpack Not Too Complicated 2

### ISSUE THREAD

**Issue by Swat99Swat** [Darkhax-Minecraft/BadMobs#79]
I decided to add your mod to the Not Too Complicated 2 modpack. Thereby removing a few constantly appearing monsters. But nothing happened, the game restarted the file tried to change manually and through the config in the game itself, but all to no avail. 
Tell me what could be the reason.
![изображение_2023-11-11_131802062](https://github.com/Darkhax-Minecraft/BadMobs/assets/17888700/590aba3e-1edc-40de-aa73-8a57d5479ce6)
![изображение_2023-11-11_131903305](https://github.com/Darkhax-Minecraft/BadMobs/assets/17888700/65f88b16-319c-4fbc-b9c3-768ffc715252)

**Comment by Darkhax** [comment]
Hello, I've downloaded the modpack and added Bad Mobs myself to try it out. Everything was working as intended and I was able to disable bats, zombies, and a few other mods. The config file being reset typically means you didn't save the file or made an issue or typo in the config file. It's also possible that there was an issue with this config editor mod that was recently fixed.
