### ISSUE TITLE
[QUESTION] "removeAggressively" not in the config?

### ISSUE THREAD

**Issue by Looodon** [Darkhax-Minecraft/BadMobs#85]
### Question

Hey in the badmobs-common.toml file there used to be a "removeAggressively" option in 1.19.2, but not 1.20.1. Is this feature removed? I liked it because it prevents spawning from mods, not just normal, spawners, and eggs

**Comment by Darkhax** [comment]
This feature was removed from 1.20.1 because it is now the default behaviour.
